### ISSUE TITLE
EventStore support

### ISSUE THREAD

**Issue by Rajivhost** [nvivo/Even#1]
Hi,
Nice framwork, any plan to provide a storage for EventStore?

**Comment by nvivo** [comment]
Hi @Rajivhost, this is definitely possible.

The format of the event is heavily based on EventStore, so writing the interface shouldn't be a problem. But projections are processed on .NET, so some of the eventstore features wouldn't be so useful. Projections would be a regular stream generated by the library where events link to events in other streams. Needs some testing to see how that would work.

So, using EventStore is something I considered when designing it, but it's not on my plans for the first releases.

**Comment by Rajivhost** [comment]
Ok, I figure out. So for, no nuget release?

**Comment by nvivo** [comment]
Life got in the way in the last weeks, but I hope I can release the first alpha to nuget in the next 2 weeks or so. Let's see, no promises.

**Comment by Rajivhost** [comment]
Ok, why not support for NET45?

**Comment by nvivo** [comment]
I just created the project using the current framework. Maybe I'll downgrade later if it makes sense.
