### ISSUE TITLE
Downgrade Even to at least .NET 4.5.2

### ISSUE THREAD

**Issue by DamianReeves** [nvivo/Even#10]
I think the .NET 4.6 entry point for Even is a bit too high. Can this be relaxed to be .NET 4.5.2 at least?

**Comment by nvivo** [comment]
Since this is experimental for now, I thought it wouldn't hurt to use the latest version. But there is not much use of 4.6 features.

Probably most (or all) of the changes would be replacing `Task.CompletedTask` for `Task.FromResult(1)`.

If you want to create a PR for that,  I'll accept it.
