### ISSUE TITLE
How do you query a projection?

### ISSUE THREAD

**Issue by DamianReeves** [nvivo/Even#8]
How are you supposed to query a projection without resorting to actor selection?

**Comment by nvivo** [comment]
The gateway has a `Query` method that uses the eventstream to publish the query to actors that can answer. The projection has an `OnQuery<>` method that subscribes to these messages.  The first actor to answer wins. The idea is more to avoid actorselection than having multiple actors answering the same query.

**Comment by DamianReeves** [comment]
So what is OnReady for in the Projections? The sample has the Query handler there.

**Comment by nvivo** [comment]
When the projection starts, it's in a state when only events to rebuild can be received,  anything else is stashed.  Once the projection finishes rebuilding, it "becomes ready" and regular messages or queries can be received. 

OnReady is supposed to be an extension point that runs when the projection enters this "ready state" that you can use to register your own Receive methods for other messages you may need (gather statistics for example). But queries have a more first class support inside projections.

**Comment by DamianReeves** [comment]
Cool, thanks.
